name: growtopia
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  adaptive_theme: ^3.3.0
  cached_network_image: ^3.2.3
  device_info_plus: ^9.0.3
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_keychain: ^2.2.1
  get: ^4.6.5
  get_storage: ^2.1.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  package_info: ^2.0.2
  pull_to_refresh: ^2.0.0
  supabase_flutter: ^1.10.14
  url_launcher: ^6.1.12

  flame: ^1.14.0
  flame_forge2d: ^0.15.1
  shared_preferences: ^2.2.2
  sensors_plus: ^4.0.2
  flame_gdx_texture_packer: ^0.6.1

  flutter_localizations:
    sdk: flutter
  crypto: ^3.0.3
  sign_in_with_apple: ^5.0.0
  audioplayers: ^5.1.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0+1
  vibration: ^1.8.1
  flutter_bounceable: ^1.1.0
  just_audio: ^0.9.34
  just_audio_cache:
    git:
      url: https://github.com/toandk/just_audio_cache.git
      ref: fix-cache-file
  lottie: ^2.6.0
  image_picker: ^1.0.4
  purchases_flutter: ^5.6.5
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.7
  confetti: ^0.7.0
  floating_bubbles: ^2.5.1
  flutter_launcher_icons: ^0.13.1
  salomon_bottom_bar: ^3.3.2
  webview_flutter: ^4.4.2
  google_sign_in: ^6.1.6
  neon_widgets: ^2.0.0
  google_mobile_ads: ^4.0.0
  percent_indicator: ^4.2.3
  dot_navigation_bar: ^1.0.2
  flutter_google_wallet: ^0.1.2
  android_id: ^0.3.6
  google_wallet:
    git:
      url: https://github.com/google-wallet/flutter-plugin.git
      ref: 50e18a5d3071f3c6aa84fb6a22829c4f8d6727f3
  dart_jsonwebtoken: ^2.13.0
  uuid: ^4.3.3
  ninepatch_image: ^0.0.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/sounds/
    - assets/text/
    - assets/
    - assets/ui/
    - packages/flutter_google_wallet/assets/svg/button/frFR_add_to_google_wallet_wallet-button.svg
    - packages/flutter_google_wallet/assets/svg/button/enUS_add_to_google_wallet_wallet-button.svg
    # - packages/google_wallet/assets/en_US_wallet_button_condensed.svg

  fonts:
    - family: DaveysDoodleface
      fonts:
        - asset: assets/fonts/DaveysDoodleface.ttf
    - family: BoldenVan
      fonts:
        - asset: assets/fonts/BoldenVan.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Black.ttf
          weight: 900
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoRegular.ttf
        - asset: assets/fonts/NunitoSemibold.ttf
          weight: 500
        - asset: assets/fonts/NunitoBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoBlack.ttf
          weight: 900
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/icon/icon.png'
    background_color: '#FFFFFF'
    theme_color: '#FFFFFF'
  windows:
    generate: true
    image_path: 'assets/icon/icon.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/icon/icon.png'
